#!/usr/bin/env python3
import os
from os import system
import blessings
from blessings import Terminal
import tempfile
dir=os.path.dirname(os.path.realpath(__file__))
info_path=dir + "/ofetch-get-info.sh"
system('reset')

#rainbow style
logo_colors=[10,10,10,11,11,3,3,9,9,8,8,12,12,12,5]

#gray
#logo_colors=[7,7,7,7,7,7,7,7,7,7,7,7,7,7,7]

logo_lines=["                :++++.         ",
"               /+++/.          ",
"       .:-::- .+/:-\`\`.::-    ",
"    .:/++++++/::::/++++++/:\`  ",
"  .:///////////////////////:\` ",
"  ////////////////////////\`   ",
" -+++++++++++++++++++++++\`    ",
" /++++++++++++++++++++++/      ",
" /sssssssssssssssssssssss.     ",
" :ssssssssssssssssssssssss-    ",
"  osssssssssssssssssssssssso/\\",
"  \`syyyyyyyyyyyyyyyyyyyyyyyy+\\",
"   \`ossssssssssssssssssssss/   ",
"     :ooooooooooooooooooo+.    ",
"      \`:+oo+/:-..-:/+o+/-   "]
term = Terminal()

infos = ["MACOS", "MODEL", "CPU", "GPU", "THERM", "BREW", "DISK", "SHELL", "TERM"]

tempfile = tempfile.NamedTemporaryFile(mode = 'w')
readfile = open(tempfile.name)

logo_width=0
line=0
for i in logo_lines:
#    print(str(line) + ": " + term.color(logo_colors[line]) + i + term.normal)
    print(term.color(logo_colors[line]) + i + term.normal)
    line = line + 1
    if len(i) > logo_width:
        logo_width=len(i)
XText = logo_width + 3


row = 0;
for i in infos:
    #print("about to do " + i + "on row " + str(row))
    system(info_path + " " + i + " >> " + tempfile.name)
    with term.location(XText,y=row):
        print(term.bold_underline(i.rjust(5)) + ": " + term.green + readfile.readline() + term.normal)
    row = row + 1
#pint(tempfile.name)
#system("cat " + tempfile.name)
tempfile.close()
readfile.close()

#os.execvp('imgcat', ["1","./small.png"])


